apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iot-server-demo-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iot-server-demo
        version: v1
    spec:
      containers:
        - name: iot-server-demo
          image: navicore/iot-server-demo
          imagePullPolicy: Always
          env:
          - name: BOOTSTRAP
            value: "CHANGE_ME"
          - name: CONSUMER_GROUP
            value: "CHANGE_ME"
          ports:
          - containerPort: 8080

