apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: iot-server-demo
  name: iot-server-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: iot-server-demo
  template:
    metadata:
      labels:
        run: iot-server-demo
    spec:
      containers:
        - name: iot-server-demo
          image: navicore/iot-server-demo
          imagePullPolicy: Always
          env:
          - name: BOOTSTRAP
            value: "kafka-s03:9092"
          - name: CONSUMER_GROUP
            value: "iot-server-demo"
