kind: Service
apiVersion: v1
metadata:
  labels:
    run: iot-server-demo
  name: iot-server-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    run: iot-server-demo

